version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  save_hello_world_output:
    environment:
      message: hello_wach_saved_output
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Display Hello
          command: |
            echo $message > output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - wach/work

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Display workspace contents
          command: |
            cat output.txt

workflows:
  welcome:
    jobs:
      - welcome/run
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
