version: 2.1

commands:
  print_pipeline_id:
    parameters:
      id:
        type: string
    steps:
      - run: echo << parameters.id >>

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  save_hello_world_output:
    environment:
      message: hello_wach_saved_output
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Display Hello
          command: |
            echo $message > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Testing whatsapp message
          command: |
            curl -d "Hey Team Lead, Wach pipeline just failed" -H "Content-Type: application/x-www-form-urlencoded" -X POST https://wa.me/8118016342
      - run:
          name: Display workspace contents
          command: |
            cat ~/output.txt
            return 1
      - print_pipeline_id:
          id: << pipeline.id >>
      - run:
          name: Action on fail
          command: |
            echo "Hey Wach, sorry for your failed pipeline"
          when: on_fail

workflows:
  welcome:
    jobs:
      - welcome/run
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
